/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.config.BeanConfig;
import org.example.scan.ServiceFacade;
import org.example.service.DateService;
import org.example.service.GreetingService;
import org.example.service.JdbcService;
import org.example.service.UidService;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class JdbcApp {

  public static void main(String[] args) {
    AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
    context.registerShutdownHook();

    context.getEnvironment().setActiveProfiles("jdbc");
    context.register(BeanConfig.class);
    context.refresh();

    JdbcService service = context.getBean(JdbcService.class);
    service.createPersonTable();
    service.createPerson(1, "Tom", "tom@email.com", 27);
    System.out.println("Persons:" + service.getPersonCount());
    System.out.println(service.getPersonMap(1));
    System.out.println(service.findPersonById(1));
    service.createPerson(2, "Mark", "mark@email.com", 29);
    System.out.println(service.getPersonList());
  }
}
