/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.config.BeanConfig;
import org.example.scan.ServiceFacade;
import org.example.service.DateService;
import org.example.service.GreetingService;
import org.example.service.JdbcService;
import org.example.service.UidService;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class JdbcApp {

  public static void main(String[] args) {
    AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
    context.registerShutdownHook();

    context.getEnvironment().setActiveProfiles("jdbc");
    context.register(BeanConfig.class);
    context.refresh();

    JdbcService service = context.getBean(JdbcService.class);
    service.createPersonTable();
  }
}
